name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때만 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot project
        run: ./gradlew clean build -x test

      - name: Copy Spring jar to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "build/libs/*.jar"
          target: "/home/ubuntu/back_ssakssak/build/libs/"

      - name: Checkout frontend repo
        uses: actions/checkout@v3
        with:
          repository: betaa0528/front_ssakssak
          path: front_ssakssak

      - name: Build frontend
        run: |
          cd front_ssakssak
          npm install
          npm run build

      - name: Copy Vue dist to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "front_ssakssak/dist/*"
          target: "/home/ubuntu/front_ssakssak/dist/"

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            bash /home/ubuntu/deploy/deploy.sh
